version: "2"
services:
  recommender:
    build:
      context: ./recommenderAPI/
    volumes:
      - ./recommenderAPI:/usr/src/app
    restart: always
    ports:
      - "5000:5000"
  node:
    build:
      context: ./node/
    volumes:
      - ./node:/usr/src/app
    restart: always
    ports:
      - "4000:4000"    
    depends_on:
      - recommender
    links:
      - recommender
  client:
    build:
      context: ./client/
    command: nginx -g "daemon off;"
    # command: npm start
    restart: always
    volumes:
      - ./client:/app/src
    depends_on:
      - node
    links:
      - node       
    expose:
      - 80
    ports:
      - "80:80"
